"""
AgentLens CI Check
Fetches latest session results, computes score, posts PR comment,
sets GitHub Actions outputs, and exits non-zero if checks fail.
"""
import os
import sys
import json
import subprocess

try:
    import httpx
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "httpx", "-q"])
    import httpx


SERVER = os.environ.get("AGENTLENS_SERVER", "http://localhost:8766")
FAIL_ON_HALLUCINATION = os.environ.get("FAIL_ON_HALLUCINATION", "true").lower() == "true"
MAX_COST = float(os.environ.get("MAX_COST_USD", "1.00"))
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_REPOSITORY = os.environ.get("GITHUB_REPOSITORY", "")
GITHUB_REF = os.environ.get("GITHUB_REF", "")
GITHUB_OUTPUT = os.environ.get("GITHUB_OUTPUT", "")


def get_latest_session() -> dict:
    try:
        r = httpx.get(f"{SERVER}/api/v1/sessions?limit=1", timeout=10)
        r.raise_for_status()
        sessions = r.json()
        return sessions[0] if sessions else {}
    except Exception as e:
        print(f"Warning: Could not fetch sessions: {e}")
        return {}


def get_score(session_id: str) -> dict:
    try:
        r = httpx.get(f"{SERVER}/api/v1/score/{session_id}", timeout=10)
        r.raise_for_status()
        return r.json()
    except Exception as e:
        print(f"Warning: Could not fetch score: {e}")
        return {}


def post_pr_comment(body: str) -> None:
    """Post a comment on the current PR using GitHub REST API."""
    if not GITHUB_TOKEN or not GITHUB_REPOSITORY:
        return
    # Extract PR number from GITHUB_REF (refs/pull/123/merge)
    parts = GITHUB_REF.split("/")
    if len(parts) < 3 or parts[1] != "pull":
        print("Not a PR context — skipping comment")
        return
    pr_number = parts[2]
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/issues/{pr_number}/comments"
    try:
        r = httpx.post(
            url,
            json={"body": body},
            headers={
                "Authorization": f"Bearer {GITHUB_TOKEN}",
                "Accept": "application/vnd.github.v3+json",
            },
            timeout=15,
        )
        if r.status_code not in (200, 201):
            print(f"Warning: PR comment failed with HTTP {r.status_code}")
    except Exception as e:
        print(f"Warning: Could not post PR comment: {e}")


def set_output(key: str, value: str) -> None:
    if GITHUB_OUTPUT:
        with open(GITHUB_OUTPUT, "a") as f:
            f.write(f"{key}={value}\n")
    else:
        print(f"OUTPUT: {key}={value}")


def build_comment(session: dict, score: dict) -> str:
    s = score.get("score", 0)
    grade = score.get("grade", "?")
    halluc = score.get("hallucination_count", 0)
    errors = score.get("error_count", 0)
    cost = session.get("total_cost_usd", 0)
    agent = session.get("agent_name", "agent")

    halluc_status = "✅" if halluc == 0 else "❌"
    cost_status = "✅" if cost <= MAX_COST else "❌"
    overall = "✅ Passed" if (
        (halluc == 0 or not FAIL_ON_HALLUCINATION) and cost <= MAX_COST
    ) else "❌ Failed"

    return f"""## AgentLens Trace Report {overall}

**Agent:** `{agent}` | **Session:** `{session.get('id', '?')[:12]}...`

| Metric | Value | Status |
|--------|-------|--------|
| Reliability Score | **{s}/100 (Grade {grade})** | {'✅' if s >= 75 else '⚠️'} |
| Hallucinations | {halluc} | {halluc_status} |
| Errors | {errors} | {'✅' if errors == 0 else '⚠️'} |
| Session Cost | ${cost:.4f} (limit: ${MAX_COST:.2f}) | {cost_status} |

<details>
<summary>Score Breakdown</summary>

Hallucination penalty: −{score.get('penalty_breakdown', {}).get('hallucinations', 0)}
Error penalty: −{score.get('penalty_breakdown', {}).get('errors', 0)}
Zero-issues bonus: +{score.get('penalty_breakdown', {}).get('zero_issues_bonus', 0)}

</details>

_Generated by [AgentLens](https://github.com/ArkFelix7/agentlens) — open-source AI agent observability_"""


if __name__ == "__main__":
    session = get_latest_session()
    if not session:
        print("No session found — agent may not have instrumented with agentlens-sdk")
        sys.exit(0)

    score = get_score(session.get("id", ""))
    comment = build_comment(session, score)
    print(comment)

    set_output("score", str(score.get("score", 0)))
    set_output("hallucination-count", str(score.get("hallucination_count", 0)))
    set_output("total-cost-usd", str(session.get("total_cost_usd", 0)))
    set_output("session-id", session.get("id", ""))

    if GITHUB_TOKEN:
        post_pr_comment(comment)

    # Determine pass/fail
    fail = False
    halluc_count = score.get("hallucination_count", 0)
    total_cost = session.get("total_cost_usd", 0)

    if FAIL_ON_HALLUCINATION and halluc_count > 0:
        print(f"\nFAIL: {halluc_count} hallucination(s) detected")
        fail = True
    if total_cost > MAX_COST:
        print(f"\nFAIL: Cost ${total_cost:.4f} exceeds limit ${MAX_COST:.2f}")
        fail = True

    if not fail:
        print("\nPASS: All AgentLens checks passed")

    sys.exit(1 if fail else 0)
